// Reserve constants
export const BATTLE_PAYMENTS = 'BATTLE_PAYMENTS';
export const ADDITIONAL_BRIEFING = 'ADDITIONAL_BRIEFING';
export const TACTICAL_TRAINING = 'TACTICAL_TRAINING';
export const MILITARY_MANEUVERS = 'MILITARY_MANEUVERS';