export const SET_PROFILE = 'SET_PROFILE';

export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const UNSET_PROFILE_LOADING = 'UNSET_PROFILE_LOADING';

export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';
export const UNSET_PROFILE_ERROR = 'UNSET_PROFILE_ERROR';

export const SET_MAIN_DRAWER = 'SET_MAIN_DRAWER';
